service: ${SERVICE_NAME}
runtime: python313
entrypoint: ${ENTRYPOINT}
service_account: "${CLOUD_SQL_USER}.gserviceaccount.com"
instance_class: F4
inbound_services:
  - warmup
automatic_scaling:
  min_instances: ${MIN_INSTANCES}
  max_instances: ${MAX_INSTANCES}
  max_concurrent_requests: 6
handlers:
  - url: /.*
    secure: always
    script: auto
env_variables:
  MODE: "production"
  ENVIRONMENT: "${ENVIRONMENT}"
  APP_VERSION: "${APP_VERSION}"
  DB_DRIVER: "cloudsql"
  CLOUD_SQL_INSTANCE_NAME: "${CLOUD_SQL_INSTANCE_NAME}"
  CLOUD_SQL_DATABASE: "${CLOUD_SQL_DATABASE}"
  CLOUD_SQL_USER: "${CLOUD_SQL_USER}"
  PYGEOAPI_POSTGRES_DB: "${PYGEOAPI_POSTGRES_DB}"
  PYGEOAPI_POSTGRES_USER: "${PYGEOAPI_POSTGRES_USER}"
  PYGEOAPI_POSTGRES_HOST: "${PYGEOAPI_POSTGRES_HOST}"
  PYGEOAPI_POSTGRES_PORT: "${PYGEOAPI_POSTGRES_PORT}"
  PYGEOAPI_POSTGRES_PASSWORD: |-
    ${PYGEOAPI_POSTGRES_PASSWORD}
  PYGEOAPI_SERVER_URL: "${PYGEOAPI_SERVER_URL}"
  CLOUD_SQL_IAM_AUTH: "${CLOUD_SQL_IAM_AUTH}"
  GCS_SERVICE_ACCOUNT_KEY: |-
    ${GCS_SERVICE_ACCOUNT_KEY}
  GCS_BUCKET_NAME: "${GCS_BUCKET_NAME}"
  AUTHENTIK_URL: "${AUTHENTIK_URL}"
  AUTHENTIK_CLIENT_ID: "${AUTHENTIK_CLIENT_ID}"
  AUTHENTIK_AUTHORIZE_URL: "${AUTHENTIK_AUTHORIZE_URL}"
  AUTHENTIK_TOKEN_URL: "${AUTHENTIK_TOKEN_URL}"
  SESSION_SECRET_KEY: |-
    ${SESSION_SECRET_KEY}
  APITALLY_CLIENT_ID: "${APITALLY_CLIENT_ID}"
