"""
aem_ingest.parsers.common — Shared constants and coordinate helpers.

Used by all three parsers.  Keeps coordinate math in one place so
the CRS logic doesn't get duplicated (or subtly diverge).
"""

from __future__ import annotations

import logging

import numpy as np
import pandas as pd
from pyproj import Transformer

logger = logging.getLogger(__name__)

# All surveys are in UTM Zone 13N.  GIP/SkyTEM and AGF deliver NAD83
# (EPSG:26913).  GeoTech/Seogi delivers WGS84 UTM 13N (EPSG:32613).
# The ~1 m difference between datums matters for cross-survey consistency,
# so we reproject Seogi data to 26913 at ingest.
TARGET_EPSG = 26913

# Canonical column names for the PostGIS aem_soundings table.
# sounding_id and loaded_at are auto-generated by the database.
CANONICAL_COLUMNS = [
    "survey_id",
    "processing_stage",
    "inversion_code",
    "contractor",
    "source_file",
    "source_epsg",
    "line_id",
    "record_id",
    "layer_no",
    "easting_m",
    "northing_m",
    "longitude_dd",
    "latitude_dd",
    "elevation_m",
    "sensor_alt_m",
    "terrain_clear_m",
    "depth_top_m",
    "depth_bot_m",
    "thickness_m",
    "resistivity_ohmm",
    "resistivity_std",
    "conductivity_sm",
    "doi_conservative_m",
    "doi_standard_m",
    "resdata",
    "restotal",
    "plni",
    "date_acquired",
]


# ---------------------------------------------------------------------------
# Coordinate helpers
# ---------------------------------------------------------------------------


def add_latlon(df: pd.DataFrame, source_epsg: int) -> pd.DataFrame:
    """Add longitude_dd and latitude_dd by transforming easting/northing to WGS84.

    Used for Format A and C where source_epsg == TARGET_EPSG (26913),
    so easting/northing don't change — we just compute WGS84 lat/lon.
    """
    transformer = Transformer.from_crs(
        f"EPSG:{source_epsg}", "EPSG:4326", always_xy=True
    )
    lon, lat = transformer.transform(df["easting_m"].values, df["northing_m"].values)
    df["longitude_dd"] = lon
    df["latitude_dd"] = lat
    return df


def reproject_and_add_latlon(df: pd.DataFrame, source_epsg: int) -> pd.DataFrame:
    """Reproject easting/northing to TARGET_EPSG (26913) and add WGS84 lat/lon.

    Used for Format B (Seogi) where source is EPSG:32613 (WGS84 UTM 13N).
    The difference between WGS84 and NAD83 is ~1 m — small but real.
    We record the original CRS in source_epsg for provenance.
    """
    # Step 1: Reproject UTM coords to NAD83 UTM 13N
    to_target = Transformer.from_crs(
        f"EPSG:{source_epsg}", f"EPSG:{TARGET_EPSG}", always_xy=True
    )
    new_e, new_n = to_target.transform(df["easting_m"].values, df["northing_m"].values)
    df["easting_m"] = new_e
    df["northing_m"] = new_n

    # Step 2: Compute WGS84 lat/lon from the reprojected coords
    to_wgs84 = Transformer.from_crs(f"EPSG:{TARGET_EPSG}", "EPSG:4326", always_xy=True)
    lon, lat = to_wgs84.transform(new_e, new_n)
    df["longitude_dd"] = lon
    df["latitude_dd"] = lat

    return df


def ensure_canonical_columns(df: pd.DataFrame) -> pd.DataFrame:
    """Add any missing canonical columns as NaN/None.

    Different formats produce different subsets of the canonical schema.
    Seogi has no uncertainty; byLayer may lack DOI; AGF has everything.
    This ensures every canonical column exists so downstream code can
    safely reference any column without KeyError.
    """
    for col in CANONICAL_COLUMNS:
        if col not in df.columns:
            df[col] = np.nan
    return df
