# ==============================================================================
# Copyright 2026 ross
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""
Transfer AssociatedData from NM_Aquifer to NMA_AssociatedData.

Updated for Integer PK schema:
- id: Integer PK (autoincrement, generated by DB)
- nma_assoc_id: Legacy UUID PK (AssocID), UNIQUE for audit
- nma_location_id: Legacy LocationId UUID, UNIQUE
- nma_point_id: Legacy PointID string
- nma_object_id: Legacy OBJECTID, UNIQUE
"""

from __future__ import annotations

from typing import Any, Optional
from uuid import UUID

import pandas as pd
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.orm import Session

from db import NMA_AssociatedData, Thing
from db.engine import session_ctx
from transfers.logger import logger
from transfers.transferer import Transferer
from transfers.util import replace_nans


class AssociatedDataTransferer(Transferer):
    """Transfer legacy AssociatedData rows from NM_Aquifer."""

    source_table = "AssociatedData"

    def __init__(self, *args, batch_size: int = 1000, **kwargs):
        super().__init__(*args, **kwargs)
        self.batch_size = batch_size
        self._thing_id_cache: dict[str, int] = {}
        self._build_thing_id_cache()

    def _build_thing_id_cache(self) -> None:
        with session_ctx() as session:
            things = session.query(Thing.name, Thing.id).all()
            self._thing_id_cache = {name: thing_id for name, thing_id in things}
        logger.info(f"Built Thing ID cache with {len(self._thing_id_cache)} entries")

    def _get_dfs(self) -> tuple[pd.DataFrame, pd.DataFrame]:
        df = self._read_csv(self.source_table)
        cleaned_df = replace_nans(df)
        return df, cleaned_df

    def _transfer_hook(self, session: Session) -> None:
        rows = [self._row_dict(row) for row in self.cleaned_df.to_dict("records")]
        rows = self._dedupe_rows(rows, key="nma_AssocID")

        if not rows:
            logger.info("No AssociatedData rows to transfer")
            return

        insert_stmt = insert(NMA_AssociatedData)
        excluded = insert_stmt.excluded

        for i in range(0, len(rows), self.batch_size):
            chunk = rows[i : i + self.batch_size]
            logger.info(
                "Upserting AssociatedData rows %s-%s (%s rows)",
                i,
                i + len(chunk) - 1,
                len(chunk),
            )
            # Upsert on nma_AssocID (legacy UUID PK, now UNIQUE)
            stmt = insert_stmt.values(chunk).on_conflict_do_update(
                index_elements=["nma_AssocID"],
                set_={
                    "nma_LocationId": excluded["nma_LocationId"],
                    "nma_PointID": excluded["nma_PointID"],
                    "Notes": excluded["Notes"],
                    "Formation": excluded["Formation"],
                    "nma_OBJECTID": excluded["nma_OBJECTID"],
                    "thing_id": excluded["thing_id"],
                },
            )
            session.execute(stmt)
        session.commit()

    def _row_dict(self, row: dict[str, Any]) -> dict[str, Any]:
        point_id = row.get("PointID")
        return {
            # Legacy UUID PK -> nma_assoc_id (unique audit column)
            "nma_AssocID": self._uuid_val(row.get("AssocID")),
            # Legacy ID columns (renamed with nma_ prefix)
            "nma_LocationId": self._uuid_val(row.get("LocationId")),
            "nma_PointID": point_id,
            "nma_OBJECTID": row.get("OBJECTID"),
            # Data columns
            "Notes": row.get("Notes"),
            "Formation": row.get("Formation"),
            # FK to Thing
            "thing_id": self._thing_id_cache.get(point_id),
        }

    def _dedupe_rows(
        self, rows: list[dict[str, Any]], key: str
    ) -> list[dict[str, Any]]:
        """Dedupe rows by unique key to avoid ON CONFLICT loops. Later rows win."""
        deduped = {}
        for row in rows:
            assoc_id = row.get(key)
            if assoc_id is None:
                continue
            deduped[assoc_id] = row
        return list(deduped.values())

    def _uuid_val(self, value: Any) -> Optional[UUID]:
        if value is None or pd.isna(value):
            return None
        if isinstance(value, UUID):
            return value
        if isinstance(value, str):
            try:
                return UUID(value)
            except ValueError:
                return None
        return None


def run(batch_size: int = 1000) -> None:
    """Entrypoint to execute the transfer."""
    transferer = AssociatedDataTransferer(batch_size=batch_size)
    transferer.transfer()


if __name__ == "__main__":
    run()

# ============= EOF =============================================
