# ==============================================================================
# Copyright 2026 ross
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ==============================================================================
"""
Transfer AssociatedData from NM_Aquifer to NMA_AssociatedData.

Updated for Integer PK schema:
- id: Integer PK (autoincrement, generated by DB)
- nma_assoc_id: Legacy UUID PK (AssocID), UNIQUE for audit
- nma_location_id: Legacy LocationId UUID, UNIQUE
- nma_point_id: Legacy PointID string
- nma_object_id: Legacy OBJECTID, UNIQUE
"""

from __future__ import annotations

from typing import Any, Optional
from uuid import UUID

import pandas as pd
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.orm import Session

from db import NMA_AssociatedData, Thing
from db.engine import session_ctx
from transfers.logger import logger
from transfers.transferer import Transferer
from transfers.util import replace_nans


class AssociatedDataTransferer(Transferer):
    """Transfer legacy AssociatedData rows from NM_Aquifer."""

    source_table = "AssociatedData"

    def __init__(self, *args, batch_size: int = 1000, **kwargs):
        super().__init__(*args, **kwargs)
        self.batch_size = batch_size
        self._thing_id_by_point_id: dict[str, int] = {}
        self._thing_id_by_location_id: dict[str, int] = {}
        self._build_thing_id_cache()

    def _build_thing_id_cache(self) -> None:
        with session_ctx() as session:
            things = session.query(Thing.id, Thing.name, Thing.nma_pk_location).all()
            for thing_id, name, nma_pk_location in things:
                if name:
                    point_key = self._normalize_point_id(name)
                    if point_key:
                        self._thing_id_by_point_id[point_key] = thing_id
                if nma_pk_location:
                    key = self._normalize_location_id(nma_pk_location)
                    if key:
                        self._thing_id_by_location_id[key] = thing_id
        logger.info(
            "Built Thing caches with %s point ids and %s location ids",
            len(self._thing_id_by_point_id),
            len(self._thing_id_by_location_id),
        )

    def _get_dfs(self) -> tuple[pd.DataFrame, pd.DataFrame]:
        df = self._read_csv(self.source_table)
        cleaned_df = replace_nans(df)
        return df, cleaned_df

    def _transfer_hook(self, session: Session) -> None:
        rows: list[dict[str, Any]] = []
        skipped_missing_thing = 0
        for raw in self.cleaned_df.to_dict("records"):
            record = self._row_dict(raw)
            if record is None:
                skipped_missing_thing += 1
                continue
            rows.append(record)

        rows = self._dedupe_rows(rows, key="nma_AssocID")

        if not rows:
            logger.info("No AssociatedData rows to transfer")
            return

        if skipped_missing_thing:
            logger.warning(
                "Skipped %s AssociatedData rows without matching Thing",
                skipped_missing_thing,
            )

        insert_stmt = insert(NMA_AssociatedData)
        excluded = insert_stmt.excluded

        for i in range(0, len(rows), self.batch_size):
            chunk = rows[i : i + self.batch_size]
            logger.info(
                "Upserting AssociatedData rows %s-%s (%s rows)",
                i,
                i + len(chunk) - 1,
                len(chunk),
            )
            # Upsert on nma_AssocID (legacy UUID PK, now UNIQUE)
            stmt = insert_stmt.values(chunk).on_conflict_do_update(
                index_elements=["nma_AssocID"],
                set_={
                    "nma_LocationId": excluded["nma_LocationId"],
                    "nma_PointID": excluded["nma_PointID"],
                    "Notes": excluded["Notes"],
                    "Formation": excluded["Formation"],
                    "nma_OBJECTID": excluded["nma_OBJECTID"],
                    "thing_id": excluded["thing_id"],
                },
            )
            session.execute(stmt)
        session.commit()

    def _row_dict(self, row: dict[str, Any]) -> Optional[dict[str, Any]]:
        point_id = row.get("PointID")
        location_id = self._uuid_val(row.get("LocationId"))
        thing_id = self._resolve_thing_id(point_id, location_id)
        if thing_id is None:
            logger.warning(
                "Skipping AssociatedData PointID=%s LocationId=%s - Thing not found",
                point_id,
                location_id,
            )
            return None

        return {
            # Legacy UUID PK -> nma_assoc_id (unique audit column)
            "nma_AssocID": self._uuid_val(row.get("AssocID")),
            # Legacy ID columns (renamed with nma_ prefix)
            "nma_LocationId": location_id,
            "nma_PointID": point_id,
            "nma_OBJECTID": row.get("OBJECTID"),
            # Data columns
            "Notes": row.get("Notes"),
            "Formation": row.get("Formation"),
            # FK to Thing
            "thing_id": thing_id,
        }

    def _resolve_thing_id(
        self, point_id: Optional[str], location_id: Optional[UUID]
    ) -> Optional[int]:
        if location_id is not None:
            key = self._normalize_location_id(str(location_id))
            thing_id = self._thing_id_by_location_id.get(key)
            if thing_id is not None:
                return thing_id
        if point_id:
            return self._thing_id_by_point_id.get(self._normalize_point_id(point_id))
        return None

    @staticmethod
    def _normalize_point_id(value: str) -> str:
        return value.strip().upper()

    @staticmethod
    def _normalize_location_id(value: str) -> str:
        return value.strip().lower()

    def _uuid_val(self, value: Any) -> Optional[UUID]:
        if value is None or pd.isna(value):
            return None
        if isinstance(value, UUID):
            return value
        if isinstance(value, str):
            try:
                return UUID(value)
            except ValueError:
                return None
        return None


def run(batch_size: int = 1000) -> None:
    """Entrypoint to execute the transfer."""
    transferer = AssociatedDataTransferer(batch_size=batch_size)
    transferer.transfer()


if __name__ == "__main__":
    run()

# ============= EOF =============================================
