# ===============================================================================
# Copyright 2026 ross
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============================================================================

from __future__ import annotations

from typing import Any, Optional
from uuid import UUID

import pandas as pd
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.orm import Session

from db import NMA_Chemistry_SampleInfo, Location
from db.engine import session_ctx
from transfers.logger import logger
from transfers.transferer import Transferer
from transfers.util import read_csv


class ChemistrySampleInfoTransferer(Transferer):
    """
    Transfer for the legacy Chemistry_SampleInfo table.

    Loads the CSV and upserts into the legacy table.

    Updated for Integer PK schema:
    - id: Integer PK (autoincrement, generated by DB)
    - nma_sample_pt_id: Legacy UUID PK (SamplePtID), UNIQUE for audit
    - nma_wclab_id: Legacy WCLab_ID
    - nma_sample_point_id: Legacy SamplePointID
    - nma_object_id: Legacy OBJECTID, UNIQUE
    - nma_location_id: Legacy LocationId UUID (for audit trail)

    FK Change (2026-01):
    - Changed from thing_id FK to location_id FK
    - 99.95% of chemistry records have valid LocationId -> Location match
    - Only ~2 truly orphan records (filtered during transfer)
    """

    source_table = "Chemistry_SampleInfo"

    def __init__(self, *args, batch_size: int = 1000, **kwargs):
        super().__init__(*args, **kwargs)
        self.batch_size = batch_size
        # Cache Location lookups to prevent N+1 queries
        self._location_id_cache = {}
        self._build_location_id_cache()

    def _build_location_id_cache(self):
        """Build cache of Location.nma_pk_location -> Location.id to prevent orphan records."""
        with session_ctx() as session:
            locations = session.query(Location.nma_pk_location, Location.id).filter(
                Location.nma_pk_location.isnot(None)
            ).all()
            normalized = {}
            for nma_pk, location_id in locations:
                if nma_pk is None:
                    continue
                # Normalize to uppercase for case-insensitive matching
                normalized_pk = str(nma_pk).strip().upper()
                if not normalized_pk:
                    continue
                if (
                    normalized_pk in normalized
                    and normalized[normalized_pk] != location_id
                ):
                    logger.warning(
                        "Duplicate Location match key '%s' for ids %s and %s",
                        normalized_pk,
                        normalized[normalized_pk],
                        location_id,
                    )
                    continue
                normalized[normalized_pk] = location_id
            self._location_id_cache = normalized
        logger.info(f"Built Location ID cache with {len(self._location_id_cache)} entries")

    def _get_dfs(self) -> tuple[pd.DataFrame, pd.DataFrame]:
        input_df = read_csv(self.source_table, parse_dates=["CollectionDate"])
        # Filter to only include rows where Location exists (prevent orphan records)
        cleaned_df = self._filter_to_valid_locations(input_df)
        cleaned_df = self._filter_to_valid_sample_pt_ids(cleaned_df)
        return input_df, cleaned_df

    def _filter_to_valid_locations(self, df: pd.DataFrame) -> pd.DataFrame:
        """
        Filter to only include rows where LocationId matches an existing Location.
        Prevents orphan ChemistrySampleInfo records.

        Uses cached Location lookups for performance.
        """
        # Use cached Location nma_pk_location values (keys of location_id_cache)
        valid_location_ids = set(self._location_id_cache.keys())

        # Normalize LocationId to uppercase for matching
        def normalize_location_id(value: Any) -> Optional[str]:
            if pd.isna(value):
                return None
            return str(value).strip().upper()

        normalized_ids = df["LocationId"].apply(normalize_location_id)

        # Filter to rows where LocationId exists in Location.nma_pk_location
        before_count = len(df)
        filtered_df = df[normalized_ids.isin(valid_location_ids)].copy()
        after_count = len(filtered_df)

        if before_count > after_count:
            skipped = before_count - after_count
            logger.warning(
                f"Filtered out {skipped} ChemistrySampleInfo records without matching Locations "
                f"({after_count} valid, {skipped} orphan records prevented)"
            )

        return filtered_df

    def _filter_to_valid_sample_pt_ids(self, df: pd.DataFrame) -> pd.DataFrame:
        """Filter to rows with a valid SamplePtID UUID (required for idempotent upserts)."""

        def _is_valid_uuid(value: Any) -> bool:
            if pd.isna(value):
                return False
            if isinstance(value, UUID):
                return True
            if isinstance(value, str):
                try:
                    UUID(value)
                    return True
                except ValueError:
                    return False
            return False

        before_count = len(df)
        filtered_df = df[df["SamplePtID"].apply(_is_valid_uuid)].copy()
        after_count = len(filtered_df)

        if before_count > after_count:
            skipped = before_count - after_count
            logger.warning(
                f"Filtered out {skipped} ChemistrySampleInfo records without valid SamplePtID "
                f"({after_count} valid, {skipped} invalid SamplePtID values)"
            )

        return filtered_df

    def _transfer_hook(self, session: Session) -> None:
        # Convert rows to dicts and filter out any without valid location_id
        row_dicts = []
        skipped_orphan_count = 0
        skipped_sample_pt_id_count = 0
        lookup_miss_count = 0
        for row in self.cleaned_df.to_dict("records"):
            row_dict = self._row_dict(row)
            if row_dict.get("nma_SamplePtID") is None:
                skipped_sample_pt_id_count += 1
                logger.warning(
                    "Skipping ChemistrySampleInfo nma_OBJECTID=%s nma_SamplePointID=%s - "
                    "nma_SamplePtID missing or invalid",
                    row_dict.get("nma_OBJECTID"),
                    row_dict.get("nma_SamplePointID"),
                )
                continue
            # Skip rows without valid location_id (orphan prevention)
            if row_dict.get("location_id") is None:
                skipped_orphan_count += 1
                lookup_miss_count += 1
                logger.warning(
                    f"Skipping ChemistrySampleInfo nma_OBJECTID={row_dict.get('nma_OBJECTID')} "
                    f"nma_LocationId={row_dict.get('nma_LocationId')} - Location not found"
                )
                continue
            row_dicts.append(row_dict)

        if skipped_sample_pt_id_count > 0:
            logger.warning(
                "Skipped %s ChemistrySampleInfo records without valid nma_SamplePtID",
                skipped_sample_pt_id_count,
            )
        if skipped_orphan_count > 0:
            logger.warning(
                f"Skipped {skipped_orphan_count} ChemistrySampleInfo records without valid Location "
                f"(orphan prevention)"
            )
        if lookup_miss_count > 0:
            logger.warning(
                "ChemistrySampleInfo Location lookup misses: %s", lookup_miss_count
            )

        rows = self._dedupe_rows(row_dicts, key="nma_OBJECTID")

        insert_stmt = insert(NMA_Chemistry_SampleInfo)
        excluded = insert_stmt.excluded

        for i in range(0, len(rows), self.batch_size):
            chunk = rows[i : i + self.batch_size]
            logger.info(
                f"Upserting batch {i}-{i+len(chunk)-1} ({len(chunk)} rows) into Chemistry_SampleInfo"
            )
            # Upsert on nma_SamplePtID (the legacy UUID PK, now UNIQUE)
            stmt = insert_stmt.values(chunk).on_conflict_do_update(
                index_elements=["nma_SamplePtID"],
                set_={
                    "location_id": excluded.location_id,  # Required FK - prevent orphans
                    "nma_SamplePointID": excluded.nma_SamplePointID,
                    "nma_WCLab_ID": excluded.nma_WCLab_ID,
                    "CollectionDate": excluded.CollectionDate,
                    "CollectionMethod": excluded.CollectionMethod,
                    "CollectedBy": excluded.CollectedBy,
                    "AnalysesAgency": excluded.AnalysesAgency,
                    "SampleType": excluded.SampleType,
                    "SampleMaterialNotH2O": excluded.SampleMaterialNotH2O,
                    "WaterType": excluded.WaterType,
                    "StudySample": excluded.StudySample,
                    "DataSource": excluded.DataSource,
                    "DataQuality": excluded.DataQuality,
                    "PublicRelease": excluded.PublicRelease,
                    "AddedDaytoDate": excluded.AddedDaytoDate,
                    "AddedMonthDaytoDate": excluded.AddedMonthDaytoDate,
                    "nma_LocationId": excluded.nma_LocationId,
                    "nma_OBJECTID": excluded.nma_OBJECTID,
                    "SampleNotes": excluded.SampleNotes,
                },
            )
            session.execute(stmt)
            session.commit()
            session.expunge_all()

    def _row_dict(self, row: dict[str, Any]) -> dict[str, Any]:
        def val(key: str) -> Optional[Any]:
            v = row.get(key)
            if pd.isna(v):
                return None
            return v

        def str_val(key: str) -> Optional[str]:
            v = val(key)
            if v is None:
                return None
            if isinstance(v, str):
                return v
            return str(v)

        def uuid_val(key: str) -> Optional[UUID]:
            v = val(key)
            if v is None:
                return None
            if isinstance(v, UUID):
                return v
            if isinstance(v, str):
                try:
                    return UUID(v)
                except ValueError:
                    return None
            return None

        def bool_val(key: str) -> Optional[bool]:
            v = val(key)
            if v is None:
                return None
            if isinstance(v, bool):
                return v
            if isinstance(v, (int, float)):
                return bool(int(v))
            if isinstance(v, str):
                normalized = v.strip().lower()
                if normalized in {"y", "yes", "true", "t", "1"}:
                    return True
                if normalized in {"n", "no", "false", "f", "0"}:
                    return False
            return None

        # Convert pandas Timestamp to datetime; native datetime stays unchanged.
        collection_date = val("CollectionDate")
        if hasattr(collection_date, "to_pydatetime"):
            collection_date = collection_date.to_pydatetime()

        # Look up Location by LocationId to prevent orphan records
        location_id_raw = val("LocationId")
        location_id = None
        if location_id_raw is not None:
            normalized_location_id = str(location_id_raw).strip().upper()
            if normalized_location_id in self._location_id_cache:
                location_id = self._location_id_cache[normalized_location_id]
            else:
                logger.debug(
                    "ChemistrySampleInfo Location lookup miss: LocationId=%s normalized=%s",
                    location_id_raw,
                    normalized_location_id,
                )

        # Map to new column names (nma_ prefix for legacy columns)
        return {
            # Legacy UUID PK -> nma_sample_pt_id (unique audit column)
            "nma_SamplePtID": uuid_val("SamplePtID"),
            # Legacy ID columns (renamed with nma_ prefix)
            "nma_WCLab_ID": str_val("WCLab_ID"),
            "nma_SamplePointID": str_val("SamplePointID"),
            "nma_LocationId": uuid_val("LocationId"),
            "nma_OBJECTID": val("OBJECTID"),
            # FK to Location
            "location_id": location_id,
            # Data columns (unchanged names)
            "CollectionDate": collection_date,
            "CollectionMethod": str_val("CollectionMethod"),
            "CollectedBy": str_val("CollectedBy"),
            "AnalysesAgency": str_val("AnalysesAgency"),
            "SampleType": str_val("SampleType"),
            "SampleMaterialNotH2O": str_val("SampleMaterialNotH2O"),
            "WaterType": str_val("WaterType"),
            "StudySample": str_val("StudySample"),
            "DataSource": str_val("DataSource"),
            "DataQuality": bool_val("DataQuality"),
            "PublicRelease": bool_val("PublicRelease"),
            "AddedDaytoDate": bool_val("AddedDaytoDate"),
            "AddedMonthDaytoDate": bool_val("AddedMonthDaytoDate"),
            "SampleNotes": str_val("SampleNotes"),
        }

    def _dedupe_rows(
        self, rows: list[dict[str, Any]], key: str
    ) -> list[dict[str, Any]]:
        """
        Deduplicate rows within a batch by the given key to avoid ON CONFLICT loops.
        Later rows win.
        """
        deduped = {}
        for row in rows:
            oid = row.get(key)
            if oid is None:
                continue
            deduped[oid] = row
        return list(deduped.values())


def run(batch_size: int = 1000) -> None:
    """Entrypoint to execute the transfer."""
    transferer = ChemistrySampleInfoTransferer(batch_size=batch_size)
    transferer.transfer()


if __name__ == "__main__":
    # Allow running via `python -m transfers.chemistry_sampleinfo`
    run()

# ============= EOF =============================================
