# ===============================================================================
# Copyright 2026 ross
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============================================================================
"""Transfer FieldParameters data from NM_Aquifer to NMA_FieldParameters.

This transfer requires ChemistrySampleInfo to be backfilled first. Each
FieldParameters record links to a ChemistrySampleInfo record via chemistry_sample_info_id.

Updated for Integer PK schema:
- id: Integer PK (autoincrement, generated by DB)
- nma_global_id: Legacy UUID PK (GlobalID), UNIQUE for audit
- chemistry_sample_info_id: Integer FK to NMA_Chemistry_SampleInfo.id
- nma_sample_pt_id: Legacy UUID FK (SamplePtID) for audit
- nma_sample_point_id: Legacy SamplePointID string
- nma_object_id: Legacy OBJECTID (Identity)
- nma_wclab_id: Legacy WCLab_ID
"""

from __future__ import annotations

from typing import Any, Optional

import pandas as pd
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.orm import Session

from db import NMA_FieldParameters
from transfers.logger import logger
from transfers.transferer import ChemistryTransferer


class FieldParametersTransferer(ChemistryTransferer):
    """
    Transfer FieldParameters records to NMA_FieldParameters.

    Looks up ChemistrySampleInfo by nma_sample_pt_id (legacy UUID) and creates linked
    FieldParameters records with Integer FK. Uses upsert for idempotent transfers.
    """

    source_table = "FieldParameters"

    def _transfer_hook(self, session: Session) -> None:
        """
        Override transfer hook to use batch upsert for idempotent transfers.

        Uses ON CONFLICT DO UPDATE on nma_GlobalID (legacy UUID PK, now UNIQUE).
        """
        df = self.cleaned_df

        row_dicts = []
        for row in df.itertuples():
            row_dict = self._row_to_dict(row)
            if row_dict is not None:
                row_dicts.append(row_dict)

        if not row_dicts:
            logger.warning("No valid rows to transfer")
            return

        rows = self._dedupe_rows(row_dicts)
        logger.info(f"Upserting {len(rows)} FieldParameters records")

        insert_stmt = insert(NMA_FieldParameters)
        excluded = insert_stmt.excluded

        for i in range(0, len(rows), self.batch_size):
            chunk = rows[i : i + self.batch_size]
            logger.info(f"Upserting batch {i}-{i+len(chunk)-1} ({len(chunk)} rows)")
            # Upsert on nma_GlobalID (legacy UUID PK, now UNIQUE)
            stmt = insert_stmt.values(chunk).on_conflict_do_update(
                index_elements=["nma_GlobalID"],
                set_={
                    "chemistry_sample_info_id": excluded.chemistry_sample_info_id,
                    "nma_SamplePtID": excluded.nma_SamplePtID,
                    "nma_SamplePointID": excluded.nma_SamplePointID,
                    "FieldParameter": excluded.FieldParameter,
                    "SampleValue": excluded.SampleValue,
                    "Units": excluded.Units,
                    "Notes": excluded.Notes,
                    "nma_OBJECTID": excluded.nma_OBJECTID,
                    "AnalysesAgency": excluded.AnalysesAgency,
                    "nma_WCLab_ID": excluded.nma_WCLab_ID,
                },
            )
            session.execute(stmt)
            session.commit()
            session.expunge_all()

    def _row_to_dict(self, row) -> Optional[dict[str, Any]]:
        """Convert a DataFrame row to a dict for upsert."""
        # Get legacy UUID FK
        legacy_sample_pt_id = self._uuid_val(getattr(row, "SamplePtID", None))
        if legacy_sample_pt_id is None:
            self._capture_error(
                getattr(row, "SamplePtID", None),
                f"Invalid SamplePtID: {getattr(row, 'SamplePtID', None)}",
                "SamplePtID",
            )
            return None

        # Look up Integer FK from cache
        chemistry_sample_info_id = self._sample_info_cache.get(legacy_sample_pt_id)
        if chemistry_sample_info_id is None:
            self._capture_error(
                legacy_sample_pt_id,
                f"ChemistrySampleInfo not found for SamplePtID: {legacy_sample_pt_id}",
                "SamplePtID",
            )
            return None

        nma_global_id = self._uuid_val(getattr(row, "GlobalID", None))
        if nma_global_id is None:
            self._capture_error(
                getattr(row, "GlobalID", None),
                f"Invalid GlobalID: {getattr(row, 'GlobalID', None)}",
                "GlobalID",
            )
            return None

        return {
            # Legacy UUID PK -> nma_global_id (unique audit column)
            "nma_GlobalID": nma_global_id,
            # New Integer FK to ChemistrySampleInfo
            "chemistry_sample_info_id": chemistry_sample_info_id,
            # Legacy ID columns (renamed with nma_ prefix)
            "nma_SamplePtID": legacy_sample_pt_id,
            "nma_SamplePointID": self._safe_str(row, "SamplePointID"),
            "nma_OBJECTID": self._safe_int(row, "OBJECTID"),
            "nma_WCLab_ID": self._safe_str(row, "WCLab_ID"),
            # Data columns
            "FieldParameter": self._safe_str(row, "FieldParameter"),
            "SampleValue": self._safe_float(row, "SampleValue"),
            "Units": self._safe_str(row, "Units"),
            "Notes": self._safe_str(row, "Notes"),
            "AnalysesAgency": self._safe_str(row, "AnalysesAgency"),
        }


def run(flags: dict = None) -> tuple[pd.DataFrame, pd.DataFrame, list]:
    """Entrypoint to execute the transfer."""
    transferer = FieldParametersTransferer(flags=flags)
    transferer.transfer()
    return transferer.input_df, transferer.cleaned_df, transferer.errors


if __name__ == "__main__":
    # Allow running via `python -m transfers.field_parameters_transfer`
    run()

# ============= EOF =============================================
