# ===============================================================================
# Copyright 2026 ross
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============================================================================
"""
Transfer MajorChemistry data from NM_Aquifer to NMA_MajorChemistry.

Updated for Integer PK schema:
- id: Integer PK (autoincrement, generated by DB)
- nma_global_id: Legacy UUID PK (GlobalID), UNIQUE for audit
- chemistry_sample_info_id: Integer FK to NMA_Chemistry_SampleInfo.id
- nma_sample_pt_id: Legacy UUID FK (SamplePtID) for audit
- nma_sample_point_id: Legacy SamplePointID string
- nma_object_id: Legacy OBJECTID, UNIQUE
- nma_wclab_id: Legacy WCLab_ID
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional

import pandas as pd
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.orm import Session

from db import NMA_MajorChemistry
from transfers.logger import logger
from transfers.transferer import ChemistryTransferer


class MajorChemistryTransferer(ChemistryTransferer):
    """
    Transfer for the legacy MajorChemistry table.

    Uses Integer FK to ChemistrySampleInfo via chemistry_sample_info_id.
    """

    source_table = "MajorChemistry"

    def __init__(self, *args, **kwargs):
        super().__init__(*args, **kwargs)
        self._parse_dates = ["AnalysisDate"]

    def _transfer_hook(self, session: Session) -> None:
        row_dicts = []
        skipped_global_id = 0
        skipped_csi_id = 0
        for row in self.cleaned_df.itertuples():
            row_dict = self._row_dict(row)
            if row_dict is None:
                continue
            if row_dict.get("nma_GlobalID") is None:
                skipped_global_id += 1
                logger.warning(
                    "Skipping MajorChemistry nma_SamplePtID=%s - nma_GlobalID missing or invalid",
                    row_dict.get("nma_SamplePtID"),
                )
                continue
            if row_dict.get("chemistry_sample_info_id") is None:
                skipped_csi_id += 1
                logger.warning(
                    "Skipping MajorChemistry nma_SamplePtID=%s - chemistry_sample_info_id not found",
                    row_dict.get("nma_SamplePtID"),
                )
                continue
            row_dicts.append(row_dict)

        if skipped_global_id > 0:
            logger.warning(
                "Skipped %s MajorChemistry records without valid nma_GlobalID",
                skipped_global_id,
            )
        if skipped_csi_id > 0:
            logger.warning(
                "Skipped %s MajorChemistry records without valid chemistry_sample_info_id",
                skipped_csi_id,
            )

        rows = self._dedupe_rows(row_dicts)
        insert_stmt = insert(NMA_MajorChemistry)
        excluded = insert_stmt.excluded

        for i in range(0, len(rows), self.batch_size):
            chunk = rows[i : i + self.batch_size]
            logger.info(
                f"Upserting batch {i}-{i+len(chunk)-1} ({len(chunk)} rows) into MajorChemistry"
            )
            # Upsert on nma_GlobalID (legacy UUID PK, now UNIQUE)
            stmt = insert_stmt.values(chunk).on_conflict_do_update(
                index_elements=["nma_GlobalID"],
                set_={
                    "chemistry_sample_info_id": excluded.chemistry_sample_info_id,
                    "nma_SamplePtID": excluded.nma_SamplePtID,
                    "nma_SamplePointID": excluded.nma_SamplePointID,
                    "Analyte": excluded.Analyte,
                    "Symbol": excluded.Symbol,
                    "SampleValue": excluded.SampleValue,
                    "Units": excluded.Units,
                    "Uncertainty": excluded.Uncertainty,
                    "AnalysisMethod": excluded.AnalysisMethod,
                    "AnalysisDate": excluded.AnalysisDate,
                    "Notes": excluded.Notes,
                    "Volume": excluded.Volume,
                    "VolumeUnit": excluded.VolumeUnit,
                    "nma_OBJECTID": excluded.nma_OBJECTID,
                    "AnalysesAgency": excluded.AnalysesAgency,
                    "nma_WCLab_ID": excluded.nma_WCLab_ID,
                },
            )
            session.execute(stmt)
            session.commit()
            session.expunge_all()

    def _row_dict(self, row: Any) -> Optional[dict[str, Any]]:
        analysis_date = getattr(row, "AnalysisDate", None)
        if analysis_date is None or pd.isna(analysis_date):
            analysis_date = None
        if hasattr(analysis_date, "to_pydatetime"):
            analysis_date = analysis_date.to_pydatetime()
        if isinstance(analysis_date, datetime):
            analysis_date = analysis_date.replace(tzinfo=None)

        # Get legacy UUID FK
        sample_pt_raw = getattr(row, "SamplePtID", None)
        legacy_sample_pt_id = self._uuid_val(sample_pt_raw)
        if legacy_sample_pt_id is None:
            self._capture_error(
                sample_pt_raw,
                f"Invalid SamplePtID: {sample_pt_raw}",
                "SamplePtID",
            )
            return None

        # Look up Integer FK from cache
        chemistry_sample_info_id = self._sample_info_cache.get(legacy_sample_pt_id)

        global_id_raw = getattr(row, "GlobalID", None)
        nma_global_id = self._uuid_val(global_id_raw)

        return {
            # Legacy UUID PK -> nma_global_id (unique audit column)
            "nma_GlobalID": nma_global_id,
            # New Integer FK to ChemistrySampleInfo
            "chemistry_sample_info_id": chemistry_sample_info_id,
            # Legacy ID columns (renamed with nma_ prefix)
            "nma_SamplePtID": legacy_sample_pt_id,
            "nma_SamplePointID": self._safe_str(row, "SamplePointID"),
            "nma_OBJECTID": self._safe_int(row, "OBJECTID"),
            "nma_WCLab_ID": self._safe_str(row, "WCLab_ID"),
            # Data columns
            "Analyte": self._safe_str(row, "Analyte"),
            "Symbol": self._safe_str(row, "Symbol"),
            "SampleValue": self._safe_float(row, "SampleValue"),
            "Units": self._safe_str(row, "Units"),
            "Uncertainty": self._safe_float(row, "Uncertainty"),
            "AnalysisMethod": self._safe_str(row, "AnalysisMethod"),
            "AnalysisDate": analysis_date,
            "Notes": self._safe_str(row, "Notes"),
            "Volume": self._safe_int(row, "Volume"),
            "VolumeUnit": self._safe_str(row, "VolumeUnit"),
            "AnalysesAgency": self._safe_str(row, "AnalysesAgency"),
        }


def run(batch_size: int = 1000) -> None:
    """Entrypoint to execute the transfer."""
    transferer = MajorChemistryTransferer(batch_size=batch_size)
    transferer.transfer()


if __name__ == "__main__":
    # Allow running via `python -m transfers.major_chemistry`
    run()

# ============= EOF =============================================
