# ===============================================================================
# Copyright 2026 ross
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============================================================================
"""
Transfer Radionuclides data from NM_Aquifer to NMA_Radionuclides.

Updated for Integer PK schema:
- id: Integer PK (autoincrement, generated by DB)
- nma_global_id: Legacy UUID PK (GlobalID), UNIQUE for audit
- chemistry_sample_info_id: Integer FK to NMA_Chemistry_SampleInfo.id
- nma_sample_pt_id: Legacy UUID FK (SamplePtID) for audit
- nma_sample_point_id: Legacy SamplePointID string
- nma_object_id: Legacy OBJECTID, UNIQUE
- nma_wclab_id: Legacy WCLab_ID
"""

from __future__ import annotations

from datetime import datetime
from typing import Any, Optional
from uuid import UUID

import pandas as pd
from sqlalchemy.dialects.postgresql import insert
from sqlalchemy.orm import Session

from db import NMA_Chemistry_SampleInfo, NMA_Radionuclides
from db.engine import session_ctx
from transfers.logger import logger
from transfers.transferer import Transferer
from transfers.util import read_csv


class RadionuclidesTransferer(Transferer):
    """
    Transfer for the legacy Radionuclides table.

    Uses Integer FK to ChemistrySampleInfo via chemistry_sample_info_id.
    """

    source_table = "Radionuclides"

    def __init__(self, *args, batch_size: int = 1000, **kwargs):
        super().__init__(*args, **kwargs)
        self.batch_size = batch_size
        # Cache: legacy UUID -> (Integer id, thing_id)
        self._sample_info_cache: dict[UUID, tuple[int, int]] = {}
        self._build_sample_info_cache()

    def _build_sample_info_cache(self) -> None:
        """Build cache of nma_sample_pt_id -> (id, thing_id) for FK lookups."""
        with session_ctx() as session:
            sample_infos = session.query(
                NMA_Chemistry_SampleInfo.nma_sample_pt_id,
                NMA_Chemistry_SampleInfo.id,
                NMA_Chemistry_SampleInfo.thing_id,
            ).filter(NMA_Chemistry_SampleInfo.nma_sample_pt_id.isnot(None)).all()
            self._sample_info_cache = {
                nma_sample_pt_id: (csi_id, thing_id)
                for nma_sample_pt_id, csi_id, thing_id in sample_infos
            }
        logger.info(
            f"Built ChemistrySampleInfo cache with {len(self._sample_info_cache)} entries"
        )

    def _get_dfs(self) -> tuple[pd.DataFrame, pd.DataFrame]:
        input_df = read_csv(self.source_table, parse_dates=["AnalysisDate"])
        cleaned_df = self._filter_to_valid_sample_infos(input_df)
        return input_df, cleaned_df

    def _filter_to_valid_sample_infos(self, df: pd.DataFrame) -> pd.DataFrame:
        valid_sample_pt_ids = set(self._sample_info_cache.keys())
        mask = df["SamplePtID"].apply(
            lambda value: self._uuid_val(value) in valid_sample_pt_ids
        )
        before_count = len(df)
        filtered_df = df[mask].copy()
        after_count = len(filtered_df)

        if before_count > after_count:
            skipped = before_count - after_count
            logger.warning(
                f"Filtered out {skipped} Radionuclides records without matching "
                f"ChemistrySampleInfo ({after_count} valid, {skipped} orphan records prevented)"
            )

        return filtered_df

    def _transfer_hook(self, session: Session) -> None:
        row_dicts = []
        skipped_global_id = 0
        skipped_thing_id = 0
        for row in self.cleaned_df.to_dict("records"):
            row_dict = self._row_dict(row)
            if row_dict is None:
                continue
            if row_dict.get("nma_GlobalID") is None:
                skipped_global_id += 1
                logger.warning(
                    "Skipping Radionuclides nma_SamplePtID=%s - nma_GlobalID missing or invalid",
                    row_dict.get("nma_SamplePtID"),
                )
                continue
            if row_dict.get("thing_id") is None:
                skipped_thing_id += 1
                logger.warning(
                    "Skipping Radionuclides nma_SamplePtID=%s - Thing not found",
                    row_dict.get("nma_SamplePtID"),
                )
                continue
            if row_dict.get("chemistry_sample_info_id") is None:
                logger.warning(
                    "Skipping Radionuclides nma_SamplePtID=%s - chemistry_sample_info_id not found",
                    row_dict.get("nma_SamplePtID"),
                )
                continue
            row_dicts.append(row_dict)

        if skipped_global_id > 0:
            logger.warning(
                "Skipped %s Radionuclides records without valid nma_GlobalID",
                skipped_global_id,
            )
        if skipped_thing_id > 0:
            logger.warning(
                "Skipped %s Radionuclides records without valid Thing",
                skipped_thing_id,
            )

        rows = self._dedupe_rows(row_dicts, key="nma_GlobalID")
        insert_stmt = insert(NMA_Radionuclides)
        excluded = insert_stmt.excluded

        for i in range(0, len(rows), self.batch_size):
            chunk = rows[i : i + self.batch_size]
            logger.info(
                f"Upserting batch {i}-{i+len(chunk)-1} ({len(chunk)} rows) into Radionuclides"
            )
            # Upsert on nma_GlobalID (legacy UUID PK, now UNIQUE)
            stmt = insert_stmt.values(chunk).on_conflict_do_update(
                index_elements=["nma_GlobalID"],
                set_={
                    "thing_id": excluded.thing_id,
                    "chemistry_sample_info_id": excluded.chemistry_sample_info_id,
                    "nma_SamplePtID": excluded.nma_SamplePtID,
                    "nma_SamplePointID": excluded.nma_SamplePointID,
                    "Analyte": excluded.Analyte,
                    "Symbol": excluded.Symbol,
                    "SampleValue": excluded.SampleValue,
                    "Units": excluded.Units,
                    "Uncertainty": excluded.Uncertainty,
                    "AnalysisMethod": excluded.AnalysisMethod,
                    "AnalysisDate": excluded.AnalysisDate,
                    "Notes": excluded.Notes,
                    "Volume": excluded.Volume,
                    "VolumeUnit": excluded.VolumeUnit,
                    "nma_OBJECTID": excluded.nma_OBJECTID,
                    "AnalysesAgency": excluded.AnalysesAgency,
                    "nma_WCLab_ID": excluded.nma_WCLab_ID,
                },
            )
            session.execute(stmt)
            session.commit()
            session.expunge_all()

    def _row_dict(self, row: dict[str, Any]) -> Optional[dict[str, Any]]:
        def val(key: str) -> Optional[Any]:
            v = row.get(key)
            if pd.isna(v):
                return None
            return v

        def float_val(key: str) -> Optional[float]:
            v = val(key)
            if v is None:
                return None
            try:
                return float(v)
            except (TypeError, ValueError):
                return None

        def int_val(key: str) -> Optional[int]:
            v = val(key)
            if v is None:
                return None
            try:
                return int(v)
            except (TypeError, ValueError):
                return None

        analysis_date = val("AnalysisDate")
        if hasattr(analysis_date, "to_pydatetime"):
            analysis_date = analysis_date.to_pydatetime()
        if isinstance(analysis_date, datetime):
            analysis_date = analysis_date.replace(tzinfo=None)

        # Get legacy UUID FK
        legacy_sample_pt_id = self._uuid_val(val("SamplePtID"))
        if legacy_sample_pt_id is None:
            self._capture_error(
                val("SamplePtID"),
                f"Invalid SamplePtID: {val('SamplePtID')}",
                "SamplePtID",
            )
            return None

        # Look up Integer FK and thing_id from cache
        cache_entry = self._sample_info_cache.get(legacy_sample_pt_id)
        chemistry_sample_info_id = cache_entry[0] if cache_entry else None
        thing_id = cache_entry[1] if cache_entry else None

        nma_global_id = self._uuid_val(val("GlobalID"))

        return {
            # Legacy UUID PK -> nma_global_id (unique audit column)
            "nma_GlobalID": nma_global_id,
            # FKs
            "thing_id": thing_id,
            "chemistry_sample_info_id": chemistry_sample_info_id,
            # Legacy ID columns (renamed with nma_ prefix)
            "nma_SamplePtID": legacy_sample_pt_id,
            "nma_SamplePointID": val("SamplePointID"),
            "nma_OBJECTID": val("OBJECTID"),
            "nma_WCLab_ID": val("WCLab_ID"),
            # Data columns
            "Analyte": val("Analyte"),
            "Symbol": val("Symbol"),
            "SampleValue": float_val("SampleValue"),
            "Units": val("Units"),
            "Uncertainty": float_val("Uncertainty"),
            "AnalysisMethod": val("AnalysisMethod"),
            "AnalysisDate": analysis_date,
            "Notes": val("Notes"),
            "Volume": int_val("Volume"),
            "VolumeUnit": val("VolumeUnit"),
            "AnalysesAgency": val("AnalysesAgency"),
        }

    def _uuid_val(self, value: Any) -> Optional[UUID]:
        if value is None or pd.isna(value):
            return None
        if isinstance(value, UUID):
            return value
        if isinstance(value, str):
            try:
                return UUID(value)
            except ValueError:
                return None
        return None

    def _dedupe_rows(
        self, rows: list[dict[str, Any]], key: str
    ) -> list[dict[str, Any]]:
        """
        Deduplicate rows within a batch by the given key to avoid ON CONFLICT loops.
        Later rows win.
        """
        deduped = {}
        for row in rows:
            row_key = row.get(key)
            if row_key is None:
                continue
            deduped[row_key] = row
        return list(deduped.values())


def run(batch_size: int = 1000) -> None:
    """Entrypoint to execute the transfer."""
    transferer = RadionuclidesTransferer(batch_size=batch_size)
    transferer.transfer()


if __name__ == "__main__":
    # Allow running via `python -m transfers.radionuclides`
    run()

# ============= EOF =============================================
