"""compare models to existing db

Revision ID: 343cd0e9896b
Revises: 66ac1af4ba69
Create Date: 2026-01-05 20:07:47.747844

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = '343cd0e9896b'
down_revision: Union[str, Sequence[str], None] = '66ac1af4ba69'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('observation', sa.Column('groundwater_level_accuracy', sa.String(length=100), nullable=True, comment='The accuracy describes the confidence in the observation value itself after the observation is obtained'))
    op.create_foreign_key(None, 'observation', 'lexicon_term', ['groundwater_level_accuracy'], ['term'], onupdate='CASCADE')
    op.create_foreign_key(None, 'sample', 'field_activity', ['field_activity_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'sample', type_='foreignkey')
    op.drop_constraint(None, 'observation', type_='foreignkey')
    op.drop_column('observation', 'groundwater_level_accuracy')
    # ### end Alembic commands ###
