"""empty message

Revision ID: 59763cc319cf
Revises: 
Create Date: 2025-07-28 11:26:12.288640

"""
from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
import sqlalchemy_utils
from sqlalchemy.orm import configure_mappers
from sqlalchemy_continuum import make_versioned
from sqlalchemy_searchable import make_searchable

# revision identifiers, used by Alembic.
revision: str = '59763cc319cf'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None

from db import *  # Import your Base from models/__init__.py
from db.engine import engine

configure_mappers()

Base.metadata.drop_all(engine)
Base.metadata.create_all(engine)


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    pass
    # ### end Alembic commands ###
