"""initial migration

Revision ID: 66ac1af4ba69
Revises:
Create Date: 2025-07-28 12:07:27.082752

"""

from typing import Sequence, Union

# from alembic import op
from sqlalchemy.orm import configure_mappers

# revision identifiers, used by Alembic.
revision: str = "66ac1af4ba69"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None



def upgrade() -> None:
    """Upgrade schema."""

    pass
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    pass
    # ### commands auto generated by Alembic - please adjust! ###

    # ### end Alembic commands ###
