"""initial migration

Revision ID: 66ac1af4ba69
Revises:
Create Date: 2025-07-28 12:07:27.082752

"""

from typing import Sequence, Union

from alembic import op

# revision identifiers, used by Alembic.
revision: str = "66ac1af4ba69"
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


# Ordered to satisfy foreign-key dependencies for CREATE TABLE.
TABLE_NAMES = [
    "aquifer_system_version",
    "geologic_formation_version",
    "lexicon_category",
    "lexicon_term",
    "location_version",
    "observation_version",
    "parameter_version",
    "pub_author",
    "regulatory_limit_version",
    "thing_version",
    "transaction",
    "analysis_method",
    "aquifer_system",
    "asset",
    "contact",
    "data_provenance",
    "geochronology_age",
    "geologic_formation",
    "lexicon_term_category_association",
    "lexicon_triple",
    "location",
    "notes",
    "parameter",
    "publication",
    "sensor",
    "status_history",
    "thing",
    "address",
    "email",
    "incomplete_nma_phone",
    "permission_history",
    "phone",
    "pub_author_contact_association",
    "regulatory_limit",
    "pub_author_publication_association",
    "asset_thing_association",
    "collaborative_network_well",
    "deployment",
    "field_event",
    "group_thing_association",
    "location_thing_association",
    "measuring_point_history",
    "monitoring_frequency_history",
    "thing_aquifer_association",
    "thing_contact_association",
    "thing_geologic_formation_association",
    "thing_id_link",
    "transducer_observation_block",
    "well_casing_material",
    "well_purpose",
    "well_screen",
    "transducer_observation",
    "field_activity",
    "field_event_participant",
    "aquifer_type",
    "sample",
    "observation",
]

TABLE_DDL = [
    """CREATE TABLE aquifer_system_version (
	name VARCHAR, 
	description TEXT, 
	primary_aquifer_type VARCHAR(100), 
	geographic_scale VARCHAR(100), 
	boundary geometry(MULTIPOLYGON,4326), 
	id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()), 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	transaction_id BIGINT NOT NULL, 
	end_transaction_id BIGINT, 
	operation_type SMALLINT NOT NULL, 
	PRIMARY KEY (id, transaction_id)
)""",
    """CREATE TABLE geologic_formation_version (
	formation_code VARCHAR(100), 
	description TEXT, 
	lithology VARCHAR(100), 
	boundary geometry(MULTIPOLYGON,4326), 
	id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()), 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	transaction_id BIGINT NOT NULL, 
	end_transaction_id BIGINT, 
	operation_type SMALLINT NOT NULL, 
	PRIMARY KEY (id, transaction_id)
)""",
    """CREATE TABLE lexicon_category (
	name VARCHAR(100) NOT NULL, 
	description VARCHAR(255), 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	PRIMARY KEY (id), 
	UNIQUE (name)
)""",
    """CREATE TABLE lexicon_term (
	term VARCHAR NOT NULL, 
	definition VARCHAR NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	PRIMARY KEY (id), 
	UNIQUE (term)
)""",
    """CREATE TABLE location_version (
	nma_pk_location VARCHAR(36), 
	description VARCHAR, 
	point geometry(POINT,4326) NOT NULL, 
	elevation FLOAT, 
	county VARCHAR(100), 
	state VARCHAR(100), 
	quad_name VARCHAR(100), 
	nma_notes_location TEXT, 
	nma_coordinate_notes TEXT, 
	nma_date_created DATE, 
	nma_site_date DATE, 
	id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()), 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	transaction_id BIGINT NOT NULL, 
	end_transaction_id BIGINT, 
	operation_type SMALLINT NOT NULL, 
	PRIMARY KEY (id, transaction_id)
)""",
    """CREATE TABLE observation_version (
	nma_pk_waterlevels VARCHAR, 
	sample_id INTEGER, 
	sensor_id INTEGER, 
	analysis_method_id INTEGER, 
	parameter_id INTEGER, 
	observation_datetime TIMESTAMP WITH TIME ZONE, 
	value FLOAT, 
	unit VARCHAR(100), 
	notes VARCHAR, 
	measuring_point_height FLOAT, 
	groundwater_level_reason VARCHAR(100), 
	id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()), 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	transaction_id BIGINT NOT NULL, 
	end_transaction_id BIGINT, 
	operation_type SMALLINT NOT NULL, 
	PRIMARY KEY (id, transaction_id)
)""",
    """CREATE TABLE parameter_version (
	parameter_name VARCHAR(100), 
	matrix VARCHAR(100), 
	parameter_type VARCHAR(100), 
	cas_number VARCHAR, 
	default_unit VARCHAR(100), 
	id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()), 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	transaction_id BIGINT NOT NULL, 
	end_transaction_id BIGINT, 
	operation_type SMALLINT NOT NULL, 
	PRIMARY KEY (id, transaction_id)
)""",
    """CREATE TABLE pub_author (
	name VARCHAR NOT NULL, 
	affiliation VARCHAR, 
	search_vector TSVECTOR, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	PRIMARY KEY (id)
)""",
    """CREATE TABLE regulatory_limit_version (
	parameter_id INTEGER, 
	limit_source VARCHAR(100), 
	limit_value NUMERIC, 
	limit_unit VARCHAR(100), 
	limit_type VARCHAR(100), 
	id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()), 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	transaction_id BIGINT NOT NULL, 
	end_transaction_id BIGINT, 
	operation_type SMALLINT NOT NULL, 
	PRIMARY KEY (id, transaction_id)
)""",
    """CREATE TABLE thing_version (
	nma_pk_welldata VARCHAR, 
	name VARCHAR, 
	thing_type VARCHAR(100), 
	first_visit_date DATE, 
	well_depth FLOAT, 
	hole_depth FLOAT, 
	well_casing_diameter FLOAT, 
	well_casing_depth FLOAT, 
	well_completion_date DATE, 
	well_driller_name VARCHAR(200), 
	well_construction_method VARCHAR(100), 
	well_pump_type VARCHAR(100), 
	well_pump_depth FLOAT, 
	formation_completion_code VARCHAR(100), 
	is_suitable_for_datalogger BOOLEAN, 
	spring_type VARCHAR(100), 
	search_vector TSVECTOR, 
	id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()), 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	transaction_id BIGINT NOT NULL, 
	end_transaction_id BIGINT, 
	operation_type SMALLINT NOT NULL, 
	PRIMARY KEY (id, transaction_id)
)""",
    """CREATE TABLE \"user\" (
	id SERIAL NOT NULL, 
	username VARCHAR(255) NOT NULL, 
	PRIMARY KEY (id)
)""",
    """CREATE TABLE analysis_method (
	analysis_method_code VARCHAR, 
	analysis_method_name VARCHAR NOT NULL, 
	analysis_method_type VARCHAR(100), 
	source_organization VARCHAR(100), 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	UNIQUE (analysis_method_code), 
	FOREIGN KEY(analysis_method_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(source_organization) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE aquifer_system (
	name VARCHAR NOT NULL, 
	description TEXT, 
	primary_aquifer_type VARCHAR(100) NOT NULL, 
	geographic_scale VARCHAR(100), 
	boundary geometry(MULTIPOLYGON,4326), 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	UNIQUE (name), 
	FOREIGN KEY(primary_aquifer_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(geographic_scale) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE asset (
	name VARCHAR NOT NULL, 
	label VARCHAR, 
	storage_service VARCHAR NOT NULL, 
	storage_path VARCHAR NOT NULL, 
	mime_type VARCHAR NOT NULL, 
	size INTEGER NOT NULL, 
	uri VARCHAR NOT NULL, 
	search_vector TSVECTOR NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE contact (
	name VARCHAR(100), 
	organization VARCHAR(100), 
	role VARCHAR(100) NOT NULL, 
	contact_type VARCHAR(100) NOT NULL, 
	nma_pk_owners VARCHAR(100), 
	nma_pk_waterlevels VARCHAR(100), 
	search_vector TSVECTOR NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_contact_name_organization UNIQUE (name, organization), 
	FOREIGN KEY(organization) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(role) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(contact_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE data_provenance (
	target_id INTEGER NOT NULL, 
	target_table VARCHAR NOT NULL, 
	field_name VARCHAR, 
	origin_type VARCHAR(100), 
	origin_source VARCHAR, 
	collection_method VARCHAR(100), 
	accuracy_value FLOAT, 
	accuracy_unit VARCHAR(100), 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(origin_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(collection_method) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(accuracy_unit) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE geochronology_age (
	location_id INTEGER NOT NULL, 
	age FLOAT NOT NULL, 
	age_error FLOAT, 
	method VARCHAR(100), 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	PRIMARY KEY (id), 
	FOREIGN KEY(method) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE geologic_formation (
	formation_code VARCHAR(100), 
	description TEXT, 
	lithology VARCHAR(100), 
	boundary geometry(MULTIPOLYGON,4326), 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	UNIQUE (formation_code), 
	FOREIGN KEY(formation_code) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(lithology) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE \"group\" (
	name VARCHAR(100) NOT NULL, 
	description VARCHAR(255), 
	project_area geometry(MULTIPOLYGON,4326), 
	group_type VARCHAR(100), 
	parent_group_id INTEGER, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	UNIQUE (name), 
	FOREIGN KEY(group_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(parent_group_id) REFERENCES \"group\" (id) ON DELETE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE lexicon_term_category_association (
	term_id INTEGER NOT NULL, 
	category_id INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	PRIMARY KEY (id), 
	FOREIGN KEY(term_id) REFERENCES lexicon_term (id) ON DELETE CASCADE, 
	FOREIGN KEY(category_id) REFERENCES lexicon_category (id) ON DELETE CASCADE
)""",
    """CREATE TABLE lexicon_triple (
	subject VARCHAR(100) NOT NULL, 
	predicate VARCHAR(100) NOT NULL, 
	object_ VARCHAR(100) NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	PRIMARY KEY (id), 
	FOREIGN KEY(subject) REFERENCES lexicon_term (term) ON DELETE CASCADE ON UPDATE CASCADE, 
	FOREIGN KEY(object_) REFERENCES lexicon_term (term) ON DELETE CASCADE ON UPDATE CASCADE
)""",
    """CREATE TABLE location (
	nma_pk_location VARCHAR(36), 
	description VARCHAR, 
	point geometry(POINT,4326) NOT NULL, 
	elevation FLOAT NOT NULL, 
	county VARCHAR(100), 
	state VARCHAR(100), 
	quad_name VARCHAR(100), 
	nma_notes_location TEXT, 
	nma_coordinate_notes TEXT, 
	nma_date_created DATE, 
	nma_site_date DATE, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE notes (
	target_id INTEGER NOT NULL, 
	target_table VARCHAR NOT NULL, 
	note_type VARCHAR(100) NOT NULL, 
	content TEXT NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(note_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE parameter (
	parameter_name VARCHAR(100) NOT NULL, 
	matrix VARCHAR(100) NOT NULL, 
	parameter_type VARCHAR(100), 
	cas_number VARCHAR, 
	default_unit VARCHAR(100) NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_parameter_name_matrix UNIQUE (parameter_name, matrix), 
	FOREIGN KEY(parameter_name) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(matrix) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(parameter_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(default_unit) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE publication (
	title TEXT NOT NULL, 
	abstract TEXT, 
	doi VARCHAR, 
	year INTEGER, 
	publisher VARCHAR, 
	url VARCHAR, 
	publication_type VARCHAR(100) NOT NULL, 
	search_vector TSVECTOR, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	PRIMARY KEY (id), 
	UNIQUE (doi), 
	FOREIGN KEY(publication_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE sensor (
	nma_pk_equipment VARCHAR(36), 
	name VARCHAR(255) NOT NULL, 
	sensor_type VARCHAR(100) NOT NULL, 
	model VARCHAR(50), 
	serial_no VARCHAR(50), 
	pcn_number VARCHAR(50), 
	owner_agency VARCHAR(100), 
	sensor_status VARCHAR(100), 
	notes TEXT, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(sensor_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	UNIQUE (serial_no), 
	UNIQUE (pcn_number), 
	FOREIGN KEY(owner_agency) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(sensor_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE status_history (
	status_type VARCHAR(100) NOT NULL, 
	status_value VARCHAR(100) NOT NULL, 
	start_date DATE NOT NULL, 
	end_date DATE, 
	reason TEXT, 
	target_id INTEGER NOT NULL, 
	target_table VARCHAR(50) NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(status_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(status_value) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE thing (
	nma_pk_welldata VARCHAR, 
	name VARCHAR NOT NULL, 
	thing_type VARCHAR(100) NOT NULL, 
	first_visit_date DATE, 
	well_depth FLOAT, 
	hole_depth FLOAT, 
	well_casing_diameter FLOAT, 
	well_casing_depth FLOAT, 
	well_completion_date DATE, 
	well_driller_name VARCHAR(200), 
	well_construction_method VARCHAR(100), 
	well_pump_type VARCHAR(100), 
	well_pump_depth FLOAT, 
	formation_completion_code VARCHAR(100), 
	is_suitable_for_datalogger BOOLEAN, 
	spring_type VARCHAR(100), 
	search_vector TSVECTOR, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(thing_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(well_construction_method) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(well_pump_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(formation_completion_code) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(spring_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE transaction (
	id BIGINT NOT NULL, 
	remote_addr VARCHAR(50), 
	user_id INTEGER, 
	issued_at TIMESTAMP WITHOUT TIME ZONE, 
	PRIMARY KEY (id), 
	FOREIGN KEY(user_id) REFERENCES \"user\" (id)
)""",
    """CREATE TABLE address (
	contact_id INTEGER NOT NULL, 
	address_line_1 VARCHAR(255) NOT NULL, 
	address_line_2 VARCHAR(255), 
	city VARCHAR(100) NOT NULL, 
	state VARCHAR(50) NOT NULL, 
	postal_code VARCHAR(20) NOT NULL, 
	country VARCHAR(50) NOT NULL, 
	address_type VARCHAR(100) NOT NULL, 
	search_vector TSVECTOR NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(contact_id) REFERENCES contact (id) ON DELETE CASCADE, 
	FOREIGN KEY(address_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE asset_thing_association (
	asset_id INTEGER NOT NULL, 
	thing_id INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	PRIMARY KEY (id), 
	FOREIGN KEY(asset_id) REFERENCES asset (id) ON DELETE CASCADE, 
	FOREIGN KEY(thing_id) REFERENCES thing (id) ON DELETE CASCADE
)""",
    """CREATE TABLE collaborative_network_well (
	actively_monitored BOOLEAN NOT NULL, 
	thing_id INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	PRIMARY KEY (id), 
	FOREIGN KEY(thing_id) REFERENCES thing (id) ON DELETE CASCADE
)""",
    """CREATE TABLE deployment (
	thing_id INTEGER NOT NULL, 
	sensor_id INTEGER NOT NULL, 
	installation_date DATE NOT NULL, 
	removal_date DATE, 
	recording_interval INTEGER, 
	recording_interval_units VARCHAR(100), 
	hanging_cable_length NUMERIC, 
	hanging_point_height NUMERIC, 
	hanging_point_description TEXT, 
	notes TEXT, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(thing_id) REFERENCES thing (id) ON DELETE CASCADE, 
	FOREIGN KEY(sensor_id) REFERENCES sensor (id), 
	FOREIGN KEY(recording_interval_units) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE email (
	contact_id INTEGER NOT NULL, 
	email VARCHAR(100) NOT NULL, 
	email_type VARCHAR(100) NOT NULL, 
	search_vector TSVECTOR NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(contact_id) REFERENCES contact (id) ON DELETE CASCADE, 
	FOREIGN KEY(email_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE field_event (
	thing_id INTEGER NOT NULL, 
	event_date TIMESTAMP WITH TIME ZONE NOT NULL, 
	notes VARCHAR, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(thing_id) REFERENCES thing (id) ON DELETE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE group_thing_association (
	group_id INTEGER NOT NULL, 
	thing_id INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	PRIMARY KEY (id), 
	FOREIGN KEY(group_id) REFERENCES \"group\" (id) ON DELETE CASCADE, 
	FOREIGN KEY(thing_id) REFERENCES thing (id) ON DELETE CASCADE
)""",
    """CREATE TABLE incomplete_nma_phone (
	contact_id INTEGER NOT NULL, 
	phone_number VARCHAR(20) NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	PRIMARY KEY (id), 
	FOREIGN KEY(contact_id) REFERENCES contact (id) ON DELETE CASCADE
)""",
    """CREATE TABLE location_thing_association (
	location_id INTEGER NOT NULL, 
	thing_id INTEGER NOT NULL, 
	effective_start TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	effective_end TIMESTAMP WITH TIME ZONE, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	PRIMARY KEY (id, location_id, thing_id), 
	FOREIGN KEY(location_id) REFERENCES location (id) ON DELETE CASCADE, 
	FOREIGN KEY(thing_id) REFERENCES thing (id) ON DELETE CASCADE
)""",
    """CREATE TABLE measuring_point_history (
	thing_id INTEGER NOT NULL, 
	measuring_point_height NUMERIC NOT NULL, 
	measuring_point_description TEXT, 
	start_date DATE NOT NULL, 
	end_date DATE, 
	reason TEXT, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(thing_id) REFERENCES thing (id) ON DELETE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE monitoring_frequency_history (
	thing_id INTEGER NOT NULL, 
	monitoring_frequency VARCHAR(100) NOT NULL, 
	start_date DATE NOT NULL, 
	end_date DATE, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(thing_id) REFERENCES thing (id) ON DELETE CASCADE, 
	FOREIGN KEY(monitoring_frequency) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE permission_history (
	contact_id INTEGER NOT NULL, 
	permission_type VARCHAR(100) NOT NULL, 
	permission_allowed BOOLEAN NOT NULL, 
	start_date DATE NOT NULL, 
	end_date DATE, 
	notes VARCHAR, 
	target_id INTEGER NOT NULL, 
	target_table VARCHAR(50) NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(contact_id) REFERENCES contact (id) ON DELETE CASCADE, 
	FOREIGN KEY(permission_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE phone (
	contact_id INTEGER NOT NULL, 
	phone_number VARCHAR(20) NOT NULL, 
	phone_type VARCHAR(100) NOT NULL, 
	search_vector TSVECTOR NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(contact_id) REFERENCES contact (id) ON DELETE CASCADE, 
	FOREIGN KEY(phone_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE pub_author_contact_association (
	author_id INTEGER NOT NULL, 
	contact_id INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	PRIMARY KEY (author_id, contact_id), 
	FOREIGN KEY(author_id) REFERENCES pub_author (id) ON DELETE CASCADE, 
	FOREIGN KEY(contact_id) REFERENCES contact (id) ON DELETE CASCADE
)""",
    """CREATE TABLE pub_author_publication_association (
	publication_id INTEGER NOT NULL, 
	author_id INTEGER NOT NULL, 
	author_order INTEGER NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	PRIMARY KEY (publication_id, author_id), 
	FOREIGN KEY(publication_id) REFERENCES publication (id) ON DELETE CASCADE, 
	FOREIGN KEY(author_id) REFERENCES pub_author (id) ON DELETE CASCADE
)""",
    """CREATE TABLE regulatory_limit (
	parameter_id INTEGER NOT NULL, 
	limit_source VARCHAR(100) NOT NULL, 
	limit_value NUMERIC NOT NULL, 
	limit_unit VARCHAR(100) NOT NULL, 
	limit_type VARCHAR(100), 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(parameter_id) REFERENCES parameter (id), 
	FOREIGN KEY(limit_source) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(limit_unit) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(limit_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE thing_aquifer_association (
	thing_id INTEGER NOT NULL, 
	aquifer_system_id INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(thing_id) REFERENCES thing (id) ON DELETE CASCADE, 
	FOREIGN KEY(aquifer_system_id) REFERENCES aquifer_system (id) ON DELETE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE thing_contact_association (
	thing_id INTEGER NOT NULL, 
	contact_id INTEGER NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	PRIMARY KEY (id), 
	FOREIGN KEY(thing_id) REFERENCES thing (id) ON DELETE CASCADE, 
	FOREIGN KEY(contact_id) REFERENCES contact (id) ON DELETE CASCADE
)""",
    """CREATE TABLE thing_geologic_formation_association (
	thing_id INTEGER NOT NULL, 
	geologic_formation_id INTEGER, 
	top_depth FLOAT NOT NULL, 
	bottom_depth FLOAT NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(thing_id) REFERENCES thing (id) ON DELETE CASCADE, 
	FOREIGN KEY(geologic_formation_id) REFERENCES geologic_formation (id) ON DELETE SET NULL, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE thing_id_link (
	thing_id INTEGER NOT NULL, 
	relation VARCHAR(100) NOT NULL, 
	alternate_id VARCHAR(100) NOT NULL, 
	alternate_organization VARCHAR(100) NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(thing_id) REFERENCES thing (id) ON DELETE CASCADE, 
	FOREIGN KEY(relation) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(alternate_organization) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE transducer_observation_block (
	thing_id INTEGER NOT NULL, 
	parameter_id INTEGER NOT NULL, 
	review_status VARCHAR(100) NOT NULL, 
	start_datetime TIMESTAMP WITH TIME ZONE NOT NULL, 
	end_datetime TIMESTAMP WITH TIME ZONE NOT NULL, 
	comment TEXT, 
	reviewer_id INTEGER, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	CONSTRAINT uq_transducer_block_thing_status_parameter_time UNIQUE (thing_id, review_status, parameter_id, start_datetime, end_datetime), 
	CONSTRAINT check_transuder_block_time_order CHECK (end_datetime > start_datetime), 
	FOREIGN KEY(thing_id) REFERENCES thing (id) ON DELETE CASCADE, 
	FOREIGN KEY(parameter_id) REFERENCES parameter (id) ON DELETE CASCADE, 
	FOREIGN KEY(review_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(reviewer_id) REFERENCES contact (id) ON DELETE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE well_casing_material (
	thing_id INTEGER NOT NULL, 
	material VARCHAR(100) NOT NULL, 
	search_vector TSVECTOR NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(thing_id) REFERENCES thing (id) ON DELETE CASCADE, 
	FOREIGN KEY(material) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE well_purpose (
	thing_id INTEGER NOT NULL, 
	purpose VARCHAR(100) NOT NULL, 
	search_vector TSVECTOR NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(thing_id) REFERENCES thing (id) ON DELETE CASCADE, 
	FOREIGN KEY(purpose) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE well_screen (
	thing_id INTEGER NOT NULL, 
	aquifer_system_id INTEGER, 
	geologic_formation_id INTEGER, 
	screen_depth_top FLOAT, 
	screen_depth_bottom FLOAT, 
	screen_type VARCHAR(100), 
	screen_description VARCHAR(1000), 
	nma_pk_wellscreens VARCHAR(100), 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(thing_id) REFERENCES thing (id) ON DELETE CASCADE, 
	FOREIGN KEY(aquifer_system_id) REFERENCES aquifer_system (id) ON DELETE SET NULL, 
	FOREIGN KEY(geologic_formation_id) REFERENCES geologic_formation (id) ON DELETE SET NULL, 
	FOREIGN KEY(screen_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE aquifer_type (
	thing_aquifer_association_id INTEGER NOT NULL, 
	aquifer_type VARCHAR(100) NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(thing_aquifer_association_id) REFERENCES thing_aquifer_association (id) ON DELETE CASCADE, 
	FOREIGN KEY(aquifer_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE field_activity (
	field_event_id INTEGER NOT NULL, 
	activity_type VARCHAR(100) NOT NULL, 
	notes VARCHAR, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(field_event_id) REFERENCES field_event (id) ON DELETE CASCADE, 
	FOREIGN KEY(activity_type) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE field_event_participant (
	field_event_id INTEGER NOT NULL, 
	contact_id INTEGER NOT NULL, 
	participant_role VARCHAR(100) NOT NULL, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(field_event_id) REFERENCES field_event (id) ON DELETE CASCADE, 
	FOREIGN KEY(contact_id) REFERENCES contact (id) ON DELETE CASCADE, 
	FOREIGN KEY(participant_role) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE transducer_observation (
	parameter_id INTEGER NOT NULL, 
	deployment_id INTEGER NOT NULL, 
	observation_datetime TIMESTAMP WITH TIME ZONE NOT NULL, 
	value FLOAT NOT NULL, 
	nma_waterlevelscontinuous_pressure_conddl_ms_cm FLOAT, 
	nma_waterlevelscontinuous_pressure_checked_by VARCHAR(4), 
	nma_waterlevelscontinuous_pressure_created TIMESTAMP WITH TIME ZONE, 
	nma_waterlevelscontinuous_pressure_data_source VARCHAR(5), 
	nma_waterlevelscontinuous_pressure_global_id VARCHAR(40), 
	nma_waterlevelscontinuous_pressure_measurement_method VARCHAR(2), 
	nma_waterlevelscontinuous_pressure_measuring_agency VARCHAR(50), 
	nma_waterlevelscontinuous_pressure_notes VARCHAR(100), 
	nma_waterlevelscontinuous_pressure_processed_by VARCHAR(4), 
	nma_waterlevelscontinuous_pressure_qced BOOLEAN, 
	nma_waterlevelscontinuous_pressure_temperature_water FLOAT, 
	nma_waterlevelscontinuous_pressure_updated TIMESTAMP WITH TIME ZONE, 
	nma_waterlevelscontinuous_pressure_water_head FLOAT, 
	nma_waterlevelscontinuous_pressure_water_head_adjusted FLOAT, 
	nma_waterlevelscontinuous_acoustic_created TIMESTAMP WITH TIME ZONE, 
	nma_waterlevelscontinuous_acoustic_data_source VARCHAR(5), 
	nma_waterlevelscontinuous_acoustic_global_id VARCHAR(40), 
	nma_waterlevelscontinuous_acoustic_measurement_method VARCHAR(2), 
	nma_waterlevelscontinuous_acoustic_measuring_agency VARCHAR(50), 
	nma_waterlevelscontinuous_acoustic_notes VARCHAR(200), 
	nma_waterlevelscontinuous_acoustic_point_id VARCHAR(50), 
	nma_waterlevelscontinuous_acoustic_pre_process_data_field FLOAT, 
	nma_waterlevelscontinuous_acoustic_public_release BOOLEAN, 
	nma_waterlevelscontinuous_acoustic_sensor_hgt_above_mp FLOAT, 
	nma_waterlevelscontinuous_acoustic_serial_no VARCHAR(50), 
	nma_waterlevelscontinuous_acoustic_server_receipt_date TIMESTAMP WITH TIME ZONE, 
	nma_waterlevelscontinuous_acoustic_speaker_to_mic_length FLOAT, 
	nma_waterlevelscontinuous_acoustic_temperature_air FLOAT, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(parameter_id) REFERENCES parameter (id) ON DELETE CASCADE, 
	FOREIGN KEY(deployment_id) REFERENCES deployment (id) ON DELETE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE sample (
	field_activity_id INTEGER NOT NULL, 
	field_event_participant_id INTEGER, 
	sample_date TIMESTAMP WITH TIME ZONE NOT NULL, 
	sample_name VARCHAR NOT NULL, 
	sample_matrix VARCHAR(100) NOT NULL, 
	sample_method VARCHAR(100) NOT NULL, 
	qc_type VARCHAR NOT NULL, 
	depth_top FLOAT, 
	depth_bottom FLOAT, 
	notes VARCHAR, 
	nma_pk_waterlevels VARCHAR, 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(field_activity_id) REFERENCES field_activity (id) ON DELETE CASCADE, 
	FOREIGN KEY(field_event_participant_id) REFERENCES field_event_participant (id), 
	UNIQUE (sample_name), 
	FOREIGN KEY(sample_matrix) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(sample_method) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
    """CREATE TABLE observation (
	nma_pk_waterlevels VARCHAR, 
	sample_id INTEGER NOT NULL, 
	sensor_id INTEGER, 
	analysis_method_id INTEGER, 
	parameter_id INTEGER NOT NULL, 
	observation_datetime TIMESTAMP WITH TIME ZONE NOT NULL, 
	value FLOAT, 
	unit VARCHAR(100) NOT NULL, 
	notes VARCHAR, 
	measuring_point_height FLOAT, 
	groundwater_level_reason VARCHAR(100), 
	id SERIAL NOT NULL, 
	created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('UTC', now()) NOT NULL, 
	created_by_name VARCHAR(255), 
	created_by_id VARCHAR(255), 
	updated_by_name VARCHAR(255), 
	updated_by_id VARCHAR(255), 
	release_status VARCHAR(100), 
	PRIMARY KEY (id), 
	FOREIGN KEY(sample_id) REFERENCES sample (id) ON DELETE CASCADE, 
	FOREIGN KEY(sensor_id) REFERENCES sensor (id) ON DELETE CASCADE, 
	FOREIGN KEY(analysis_method_id) REFERENCES analysis_method (id), 
	FOREIGN KEY(parameter_id) REFERENCES parameter (id), 
	FOREIGN KEY(unit) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(groundwater_level_reason) REFERENCES lexicon_term (term) ON UPDATE CASCADE, 
	FOREIGN KEY(release_status) REFERENCES lexicon_term (term) ON UPDATE CASCADE
)""",
]

INDEX_DDL = [
    """CREATE INDEX idx_aquifer_system_version_boundary ON aquifer_system_version USING gist (boundary)""",
    """CREATE INDEX ix_aquifer_system_version_end_transaction_id ON aquifer_system_version (end_transaction_id)""",
    """CREATE INDEX ix_aquifer_system_version_operation_type ON aquifer_system_version (operation_type)""",
    """CREATE INDEX ix_aquifer_system_version_transaction_id ON aquifer_system_version (transaction_id)""",
    """CREATE INDEX idx_geologic_formation_version_boundary ON geologic_formation_version USING gist (boundary)""",
    """CREATE INDEX ix_geologic_formation_version_end_transaction_id ON geologic_formation_version (end_transaction_id)""",
    """CREATE INDEX ix_geologic_formation_version_operation_type ON geologic_formation_version (operation_type)""",
    """CREATE INDEX ix_geologic_formation_version_transaction_id ON geologic_formation_version (transaction_id)""",
    """CREATE INDEX idx_location_version_point ON location_version USING gist (point)""",
    """CREATE INDEX ix_location_version_end_transaction_id ON location_version (end_transaction_id)""",
    """CREATE INDEX ix_location_version_operation_type ON location_version (operation_type)""",
    """CREATE INDEX ix_location_version_transaction_id ON location_version (transaction_id)""",
    """CREATE INDEX ix_observation_version_end_transaction_id ON observation_version (end_transaction_id)""",
    """CREATE INDEX ix_observation_version_operation_type ON observation_version (operation_type)""",
    """CREATE INDEX ix_observation_version_transaction_id ON observation_version (transaction_id)""",
    """CREATE INDEX ix_parameter_version_end_transaction_id ON parameter_version (end_transaction_id)""",
    """CREATE INDEX ix_parameter_version_operation_type ON parameter_version (operation_type)""",
    """CREATE INDEX ix_parameter_version_transaction_id ON parameter_version (transaction_id)""",
    """CREATE INDEX ix_pub_author_search_vector ON pub_author USING gin (search_vector)""",
    """CREATE INDEX ix_regulatory_limit_version_end_transaction_id ON regulatory_limit_version (end_transaction_id)""",
    """CREATE INDEX ix_regulatory_limit_version_operation_type ON regulatory_limit_version (operation_type)""",
    """CREATE INDEX ix_regulatory_limit_version_transaction_id ON regulatory_limit_version (transaction_id)""",
    """CREATE INDEX ix_thing_version_end_transaction_id ON thing_version (end_transaction_id)""",
    """CREATE INDEX ix_thing_version_operation_type ON thing_version (operation_type)""",
    """CREATE INDEX ix_thing_version_search_vector ON thing_version USING gin (search_vector)""",
    """CREATE INDEX ix_thing_version_transaction_id ON thing_version (transaction_id)""",
    """CREATE INDEX idx_aquifer_system_boundary ON aquifer_system USING gist (boundary)""",
    """CREATE INDEX ix_aquifersystem_name ON aquifer_system (name)""",
    """CREATE INDEX ix_asset_search_vector ON asset USING gin (search_vector)""",
    """CREATE INDEX ix_contact_search_vector ON contact USING gin (search_vector)""",
    """CREATE INDEX ix_provenance_targets ON data_provenance (target_id, target_table)""",
    """CREATE INDEX idx_geologic_formation_boundary ON geologic_formation USING gist (boundary)""",
    """CREATE INDEX ix_geologicformation_formation_code ON geologic_formation (formation_code)""",
    """CREATE INDEX idx_group_project_area ON \"group\" USING gist (project_area)""",
    """CREATE INDEX idx_location_point ON location USING gist (point)""",
    """CREATE INDEX ix_notes_polymorphic_link ON notes (target_id, target_table)""",
    """CREATE INDEX ix_publication_search_vector ON publication USING gin (search_vector)""",
    """CREATE INDEX ix_thing_search_vector ON thing USING gin (search_vector)""",
    """CREATE INDEX ix_transaction_user_id ON transaction (user_id)""",
    """CREATE INDEX ix_address_search_vector ON address USING gin (search_vector)""",
    """CREATE INDEX ix_email_search_vector ON email USING gin (search_vector)""",
    """CREATE INDEX ix_phone_search_vector ON phone USING gin (search_vector)""",
    """CREATE INDEX ix_transducer_block_time ON transducer_observation_block (start_datetime, end_datetime)""",
    """CREATE INDEX ix_transducer_observation_block_end_datetime ON transducer_observation_block (end_datetime)""",
    """CREATE INDEX ix_transducer_observation_block_parameter_id ON transducer_observation_block (parameter_id)""",
    """CREATE INDEX ix_transducer_observation_block_start_datetime ON transducer_observation_block (start_datetime)""",
    """CREATE INDEX ix_transducer_observation_block_thing_id ON transducer_observation_block (thing_id)""",
    """CREATE INDEX ix_well_casing_material_search_vector ON well_casing_material USING gin (search_vector)""",
    """CREATE INDEX ix_well_purpose_search_vector ON well_purpose USING gin (search_vector)""",
    """CREATE INDEX ix_transducer_observation_observation_datetime ON transducer_observation (observation_datetime)""",
    """CREATE INDEX ix_transducer_observation_parameter_id ON transducer_observation (parameter_id)""",
]


def upgrade() -> None:
    """Upgrade schema."""
    for ddl in TABLE_DDL:
        op.execute(ddl)
    for ddl in INDEX_DDL:
        op.execute(ddl)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    for table_name in reversed(TABLE_NAMES):
        op.execute(f'DROP TABLE IF EXISTS "{table_name}"')
    # ### end Alembic commands ###
