"""add unique constraint to NMAMinorTraceChemistry

Revision ID: 6e1c90f6135a
Revises: 95d8b982cd5d
Create Date: 2026-01-09 17:30:00.842462

"""

from typing import Sequence, Union

from alembic import op
import geoalchemy2
import sqlalchemy as sa
import sqlalchemy_utils

# revision identifiers, used by Alembic.
revision: str = "6e1c90f6135a"
down_revision: Union[str, Sequence[str], None] = "95d8b982cd5d"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(
        "uq_minor_trace_chemistry_sample_analyte",
        "NMA_MinorTraceChemistry",
        ["chemistry_sample_info_id", "analyte"],
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(
        "uq_minor_trace_chemistry_sample_analyte",
        "NMA_MinorTraceChemistry",
        type_="unique",
    )
    # ### end Alembic commands ###
