"""changes to pre-production

Revision ID: 8447b9ebaf29
Revises: 5901f059248a
Create Date: 2025-07-22 12:17:19.076090

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlalchemy_utils


# revision identifiers, used by Alembic.
revision: str = "8447b9ebaf29"
down_revision: Union[str, Sequence[str], None] = "5901f059248a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "address",
        sa.Column(
            "search_vector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_address_search_vector",
        "address",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.add_column(
        "thing",
        sa.Column(
            "search_vector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_thing_search_vector",
        "thing",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    op.add_column(
        "well_thing",
        sa.Column(
            "search_vector",
            sqlalchemy_utils.types.ts_vector.TSVectorType(),
            nullable=True,
        ),
    )
    op.create_index(
        "ix_well_thing_search_vector",
        "well_thing",
        ["search_vector"],
        unique=False,
        postgresql_using="gin",
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(
        "ix_well_thing_search_vector", table_name="well_thing", postgresql_using="gin"
    )
    op.drop_column("well_thing", "search_vector")
    op.drop_index("ix_thing_search_vector", table_name="thing", postgresql_using="gin")
    op.drop_column("thing", "search_vector")
    op.drop_index(
        "ix_address_search_vector", table_name="address", postgresql_using="gin"
    )
    op.drop_column("address", "search_vector")
    # ### end Alembic commands ###
