"""Add groundwater_level_accuracy to observation table

Revision ID: ff5701e6b9f5
Revises: 7b8c9d0e1f2a
Create Date: 2026-02-04 09:55:33.409983

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "ff5701e6b9f5"
down_revision: Union[str, Sequence[str], None] = "7b8c9d0e1f2a"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "observation",
        sa.Column(
            "groundwater_level_accuracy",
            sa.String(length=100),
            nullable=True,
            comment="The accuracy describes the confidence in the observation value itself after the observation is obtained",
        ),
    )
    op.create_foreign_key(
        None,
        "observation",
        "lexicon_term",
        ["groundwater_level_accuracy"],
        ["term"],
        onupdate="CASCADE",
    )
    op.add_column(
        "observation_version",
        sa.Column(
            "groundwater_level_accuracy",
            sa.String(length=100),
            autoincrement=False,
            nullable=True,
            comment="The accuracy describes the confidence in the observation value itself after the observation is obtained",
        ),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("observation_version", "groundwater_level_accuracy")
    op.drop_constraint(None, "observation", type_="foreignkey")
    op.drop_column("observation", "groundwater_level_accuracy")
    # ### end Alembic commands ###
