# ===============================================================================
# Copyright 2025 ross
#
# Licensed under the Apache License, Version 2.0 (the "License");
# you may not use this file except in compliance with the License.
# You may obtain a copy of the License at
#
# http://www.apache.org/licenses/LICENSE-2.0
#
# Unless required by applicable law or agreed to in writing, software
# distributed under the License is distributed on an "AS IS" BASIS,
# WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
# See the License for the specific language governing permissions and
# limitations under the License.
# ===============================================================================
from datetime import datetime
from sqlalchemy import (
    ForeignKey,
    DateTime,
    Integer,
)
from sqlalchemy.orm import mapped_column, relationship, Mapped

from db.base import Base, AutoBaseMixin, ReleaseMixin, lexicon_term

from typing import TYPE_CHECKING

if TYPE_CHECKING:
    from db.sample import Sample
    from db.sensor import Sensor
    from db.analysis_method import AnalysisMethod
    from db.parameter import Parameter


class Observation(Base, AutoBaseMixin, ReleaseMixin):
    __versioned__ = {}

    # NM_Aquifer fields for audits
    nma_pk_waterlevels: Mapped[str] = mapped_column(nullable=True)

    # --- Foreign Keys ---
    sample_id: Mapped[int] = mapped_column(
        ForeignKey("sample.id", ondelete="CASCADE"),
        nullable=False,
    )
    sensor_id: Mapped[int] = mapped_column(
        ForeignKey("sensor.id", ondelete="CASCADE"),
        nullable=True,
    )
    analysis_method_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("analysis_method.id"), nullable=True
    )

    parameter_id: Mapped[int] = mapped_column(
        Integer, ForeignKey("parameter.id"), nullable=False
    )

    # --- Columns ---
    observation_datetime: Mapped[datetime] = mapped_column(
        DateTime(timezone=True), nullable=False, doc="Timestamp of the observation"
    )
    value: Mapped[float] = mapped_column(
        nullable=True,
    )
    unit: Mapped[str] = lexicon_term(nullable=False)

    # groundwater
    measuring_point_height: Mapped[float] = mapped_column(
        nullable=True,
        doc="Height of the measuring point above the ground surface in ft",
        info={"unit": "ft"},
    )

    level_status: Mapped[str] = lexicon_term(nullable=True)

    # geothermal
    observation_depth: Mapped[float] = mapped_column(
        nullable=True,
        info={"unit": "feet"},
        doc="Depth of the geothermal observation in feet",
    )

    # --- Relationships ---
    # Many-To-One: An Observation can be generated by one piece of Equipment.
    sensor: Mapped["Sensor"] = relationship(  # noqa: F821
        "Sensor", back_populates="observations", passive_deletes=True
    )  # noqa: F821

    # Many-To-One: An Observation is derived from one Sample.
    sample: Mapped["Sample"] = relationship(  # noqa: F821
        "Sample", back_populates="observations", passive_deletes=True
    )  # noqa: F821

    # Many-To-One: An Observation can be generated using one AnalysisMethod.
    analysis_method: Mapped["AnalysisMethod"] = relationship(
        "AnalysisMethod", back_populates="observations"
    )

    # Many-To-One: An Observation measures one Parameter.
    parameter: Mapped["Parameter"] = relationship(
        "Parameter", back_populates="observations"
    )


# ============= EOF =============================================
