name: CD (Staging)

on:
  push:
    branches: [pre-production]

jobs:
    staging-deploy:

        runs-on: ubuntu-latest
        environment: staging

        steps:
        - name: Check out source repository
          uses: actions/checkout@v4
          with:
            fetch-depth: 0

        - name: Install uv in container
          uses: astral-sh/setup-uv@v6
          with:
            version: "latest"

        - name: Generate requirements.txt
          run: |
            uv export -o requirements.txt

        - name: Authenticate to Google Cloud
          uses: 'google-github-actions/auth@v2'
          with:
            credentials_json: ${{ secrets.CLOUD_DEPLOY_SERVICE_ACCOUNT_KEY }}

        # Uses Google Cloud Secret Manager to store secret credentials
        - name: Create app.yaml
          run: |
            echo "service: nmsamplelocations" > app.yaml
            echo "runtime: python313" >> app.yaml
            echo "entrypoint: gunicorn -w 4 -k uvicorn.workers.UvicornWorker main:app" >> app.yaml
            echo "instance_class: F4" >> app.yaml
            echo "" >> app.yaml
            echo "env_variables:" >> app.yaml
            echo "  MODE: \"production\"" >> app.yaml
            echo "  DB_DRIVER: \"cloudsql\"" >> app.yaml
            echo "  CLOUD_SQL_INSTANCE_NAME: \"${{ secrets.CLOUD_SQL_INSTANCE_NAME }}\"" >> app.yaml
            echo "  CLOUD_SQL_DATABASE: \"${{ secrets.CLOUD_SQL_DATABASE }}\"" >> app.yaml
            echo "  CLOUD_SQL_USER: \"${{ secrets.CLOUD_SQL_USER }}\"" >> app.yaml
            echo "  CLOUD_SQL_PASSWORD: \"${{ secrets.CLOUD_SQL_PASSWORD }}\"" >> app.yaml

        - name: Deploy to Google Cloud
          run: |
            gcloud app deploy app.yaml --quiet --project ${{ secrets.GCP_PROJECT_ID }}

        # Clean up old versions - delete only the oldest version, one created and one destroyed
        - name: Clean up oldest version
          run: |
            OLDEST_VERSION=$(gcloud app versions list --service=nmsamplelocations --project=${{ secrets.GCP_PROJECT_ID }} --format="value(id)" --sort-by="version.createTime" | head -n 1)
            if [ ! -z "$OLDEST_VERSION" ]; then
              echo "Deleting oldest version: $OLDEST_VERSION"
              gcloud app versions delete $OLDEST_VERSION --service=nmsamplelocations --project=${{ secrets.GCP_PROJECT_ID }} --quiet
              echo "Deleted oldest version: $OLDEST_VERSION"
            else
              echo "No versions to delete"
            fi

        - name: Remove app.yaml
          run: |
            rm app.yaml

        # Use PR author's username as git user name
        - name: Set up git user
          run: |
            git config --global user.name "${{ github.actor }}"
            git config --global user.email "${{ github.actor }}@users.noreply.github.com"

        # ":" are not alloed in git tags, so replace with "-"
        - name: Tag commit
          run: |
            git tag -a "staging-deploy-$(date -u +%Y-%m-%d)T$(date -u +%H-%M-%S%z)" -m "staging gcloud deployment: $(date -u +%Y-%m-%d)T$(date -u +%H:%M:%S%z)"
            git push origin --tags